/*
 *  Copyright OpenSearch Contributors
 *  SPDX-License-Identifier: Apache-2.0
 */

pluginManagement {
    repositories {
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://mirrors.huaweicloud.com/repository/maven/' }
        gradlePluginPortal()
    }
}

rootProject.name = 'opensearch-knn'

include ":qa"
include ":qa:rolling-upgrade"
include ":qa:restart-upgrade"
include ":remote-index-build-client"

