/*
 * SPDX-License-Identifier: Apache-2.0
 *
 * The OpenSearch Contributors require contributions made to
 * this file be licensed under the Apache-2.0 license or a
 * compatible open source license.
 *
 * Modifications Copyright OpenSearch Contributors. See
 * GitHub history for details.
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensearch_knn_jni_KnowhereService */

#ifndef _Included_org_opensearch_knn_jni_KnowhereService
#define _Included_org_opensearch_knn_jni_KnowhereService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensearch_knn_jni_KnowhereService
 * Method:    initLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_opensearch_knn_jni_KnowhereService_initLibrary
  (JNIEnv *, jclass);

/*
 * Class:     org_opensearch_knn_jni_KnowhereService
 * Method:    createIndex
 * Signature: ([IJILjava/lang/String;Ljava/util/Map;)V
 */
JNIEXPORT void JNICALL Java_org_opensearch_knn_jni_KnowhereService_createIndex
  (JNIEnv *, jclass, jintArray, jlong, jint, jstring, jobject);

/*
 * Class:     org_opensearch_knn_jni_KnowhereService
 * Method:    loadIndex
 * Signature: (Ljava/lang/String;Ljava/util/Map;)J
 */
JNIEXPORT jlong JNICALL Java_org_opensearch_knn_jni_KnowhereService_loadIndex
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     org_opensearch_knn_jni_KnowhereService
 * Method:    queryIndex
 * Signature: (J[FILjava/util/Map;)[Lorg/opensearch/knn/index/query/KNNQueryResult;
 */
JNIEXPORT jobjectArray JNICALL Java_org_opensearch_knn_jni_KnowhereService_queryIndex
  (JNIEnv *, jclass, jlong, jfloatArray, jint, jobject);

/*
 * Class:     org_opensearch_knn_jni_KnowhereService
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_opensearch_knn_jni_KnowhereService_free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
